app_blog_homepage:
    pattern:  /
    defaults: { _controller: AppBlogBundle:Blog:index }
    requirements:
        _method: GET

app_blog_contact:
    pattern:  /contact/
    defaults: { _controller: AppBlogBundle:Blog:contact }
    requirements:
        _method: GET|POST

app_blog_rechercher:
    pattern:  /rechercher/
    defaults: { _controller: AppBlogBundle:Blog:search }
    requirements:
        _method: GET|POST
#
# MANAGE CATEGORIE
#
categorie:
    pattern:  /categorie/{page}/
    defaults: { _controller: AppBlogBundle:Categorie:index, page: 1 }
    requirements:
        page: \d*
        _method: GET

categorie_new:
    pattern:  /categorie/new/
    defaults: { _controller: AppBlogBundle:Categorie:new}
    requirements:
        _method: GET|POST

categorie_edit:
    pattern:  /categorie/edit/{id}
    defaults: { _controller: AppBlogBundle:Categorie:edit}
    requirements:
        _method: GET|PUT

categorie_delete:
    pattern:  /categorie/delete/{id}
    defaults: { _controller: AppBlogBundle:Categorie:delete }
    requirements:
        _method: DELETE

categorie_show:
    pattern:  /categorie/show/{id}/
    defaults: { _controller: AppBlogBundle:Categorie:show}
    requirements:
        _method: GET

#
# MANAGE ARTICLE
#
article:
    pattern:  /article/{page}/
    defaults: { _controller: AppBlogBundle:Article:index, page: 1 }
    requirements:
        page: \d*
        _method: GET

article_new:
    pattern:  /article/new/
    defaults: { _controller: AppBlogBundle:Article:new}
    requirements:
        _method: GET|POST

article_edit:
    pattern:  /article/edit/{id}
    defaults: { _controller: AppBlogBundle:Article:edit}
    requirements:
        _method: GET|PUT

article_delete:
    pattern:  /article/delete/{id}
    defaults: { _controller: AppBlogBundle:Article:delete }
    requirements:
        _method: DELETE

article_show:
    pattern:  /article/show/{id}/
    defaults: { _controller: AppBlogBundle:Article:show}
    requirements:
        _method: GET

#
# MANAGE COMMENTAIRE
#
commentaire:
    pattern:  /commentaire/{page}/
    defaults: { _controller: AppBlogBundle:Commentaire:index, page: 1 }
    requirements:
        page: \d*
        _method: GET

commentaire_edit:
    pattern:  /commentaire/edit/{id}
    defaults: { _controller: AppBlogBundle:Commentaire:edit}
    requirements:
        _method: GET|PUT

commentaire_delete:
    pattern:  /commentaire/delete/{id}
    defaults: { _controller: AppBlogBundle:Commentaire:delete }
    requirements:
        _method: DELETE

commentaire_show:
    pattern:  /commentaire/show/{id}/
    defaults: { _controller: AppBlogBundle:Commentaire:show}
    requirements:
        _method: GET

#
# Affichage categorie et article blog
#
app_blog_categorie:
    pattern:  /{categorie}/
    defaults: { _controller: AppBlogBundle:Blog:categorie }
    requirements:
        _method: GET

app_blog_article:
    pattern:  /{categorie}/{article}/
    defaults: { _controller: AppBlogBundle:Blog:article }
    requirements:
        _method: GET|POST
        
