parameters:
    categorie:    10
    article:      10
    commentaire:  10
    blog.form.type.projet.class: App\BlogBundle\Form\CommentaireType
    blog_accueil_article_par_categorie: 4

services:
    # Service pour le formulaire de créaton de commentaire
    blog.form.type.projet:
        class: %blog.form.type.projet.class%
        arguments: ["@security.context"]
        tags:
            - { name: form.type, alias: commentaire }
