fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#
# ROOT PROJET #
#
userlog:
    pattern:  /log/{page}/
    defaults: { _controller: AppUserBundle:UserLog:index, page: 1 }
    requirements:
        page: \d*

#
# ROOT CLIENT
#
client:
    pattern:  /client/{page}/
    defaults: { _controller: AppUserBundle:Client:index, page: 1 }
    requirements:
        page: \d*

client_new:
    pattern:  /client/new/
    defaults: { _controller: AppUserBundle:Client:new}
    requirements:
        _method: GET|POST

client_edit:
    pattern:  /client/edit/{id}
    defaults: { _controller: AppUserBundle:Client:edit}
    requirements:
        _method: GET|PUT

client_delete:
    pattern:  /client/delete/{id}
    defaults: { _controller: AppUserBundle:Client:delete }
    requirements:
        _method: DELETE

client_show:
    pattern:  /client/show/{id}
    defaults: { _controller: AppUserBundle:Client:show}
    requirements:
        _method: GET

#
# ROOT PARTENAIRE
#
partenaire:
    pattern:  /partenaire/{page}/
    defaults: { _controller: AppUserBundle:Partenaire:index, page: 1 }
    requirements:
        page: \d*

partenaire_new:
    pattern:  /partenaire/new/
    defaults: { _controller: AppUserBundle:Partenaire:new}
    requirements:
        _method: GET|POST

partenaire_edit:
    pattern:  /partenaire/edit/{id}
    defaults: { _controller: AppUserBundle:Partenaire:edit}
    requirements:
        _method: GET|PUT

partenaire_delete:
    pattern:  /partenaire/delete/{id}
    defaults: { _controller: AppUserBundle:Partenaire:delete }
    requirements:
        _method: DELETE

partenaire_show:
    pattern:  /partenaire/show/{id}
    defaults: { _controller: AppUserBundle:Partenaire:show}
    requirements:
        _method: GET
