imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "AppPortfolioBundle:Form:form_div_layout.html.twig"
            - "AppUserBundle:Form:fields.html.twig"
            - "AppPortfolioBundle:Form:fields_user.html.twig"
            - "AppPortfolioBundle:Form:fields.html.twig"
            - "AppBlogBundle:Form:fields_user.html.twig"
            - "AppBlogBundle:Form:fields.html.twig"

# Assetic Configuration
bc_bootstrap:
    less_filter: lessphp
    assets_dir: %kernel.root_dir%/../vendor/twitter/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "AppPortfolioBundle" ]
    #java: /usr/bin/java
    filters:
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        cssrewrite: ~
    assets:            
        img_bootstrap_glyphicons_black:
            inputs:
                -  "%kernel.root_dir%/../vendor/twitter/bootstrap/img/glyphicons-halflings.png"
            output: "img/glyphicons-halflings.png"

        img_bootstrap_glyphicons_white:
            inputs:
                -  "%kernel.root_dir%/../vendor/twitter/bootstrap/img/glyphicons-halflings-white.png"
            output: "img/glyphicons-halflings-white.png"
        bootstrap_css:
            inputs:
                #- %kernel.root_dir%/../vendor/twitter/bootstrap/less/bootstrap.less
                #- %kernel.root_dir%/../vendor/twitter/bootstrap/less/responsive.less
                - %kernel.root_dir%/../vendor/twitter/bootstrap/docs/assets/css/bootstrap.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/docs/assets/css/bootstrap-responsive.css
            filters:
                - lessphp
                - cssrewrite
            output: css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-transition.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-alert.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-button.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-carousel.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-collapse.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-dropdown.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-modal.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tooltip.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-popover.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-scrollspy.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-tab.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-typeahead.js
                - %kernel.root_dir%/../vendor/twitter/bootstrap/js/bootstrap-affix.js
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.9.1.js
            output: js/jquery.js
        jquery_ui:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery-ui/jquery-ui.min.js
            output: js/jquery-ui.js
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Configuration FOSUserBundle
fos_user:
    db_driver:            orm
    firewall_name:        main
    user_class:           App\UserBundle\Entity\User
    from_email:
        address:          %webmaster_email%
        sender_name:      %webmaster_name%
    registration:
        confirmation:
            enabled:      true
        form:
            type:         registration
    profile:
        form:
            type:         profile
    resetting:
        form:
            type:         resetting
    change_password:
        form:
            type:         change_password

# TinymceBundle configuration
stfalcon_tinymce:    
    include_jquery: false
    tinymce_jquery: false
    selector: ".tinymce"
    #base_url: "http://rfid2print.localhost/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
    # Get current language from the parameters.ini
    language: %locale%    
    theme:
        # Simple theme: same as default theme
        simple: 
            theme:    "modern"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | hello_world"
        # Advanced theme with almost all enabled plugins
        advanced:
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality"
                - "emoticons template paste textcolor"
            toolbar1: "jbimages insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}            
            # Désactiver l'écriture l'url relative          
            relative_urls: false            
            #remove_script_host: false
            # Autoriser l'écriture de l'attribut style
            valid_children : "+body[style]"
            # Ajout de fichier de style CSS
            content_css: "/bundles/appblog/css/bootstrap.min.css"
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
            plugins: ["bbcode, code, link, preview"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
    # External plugin for uploding file
    external_plugins:
        jbimages:
            url: "asset[bundles/appblog/js/jbimages/plugin.js]"
