parameters:
#    app_boutique.example.class: App\BoutiqueBundle\Example

services:
#    app_boutique.example:
#        class: %app_boutique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
